export const characters = [
    {
        id: 'rebecca_chambers',
        name: 'Rebecca Chambers',
        image: '/images/characters/rebecca_chambers.png',
        affiliation: 'S.T.A.R.S. / BSAA',
        status: 'Alive',
        firstAppearance: 'Resident Evil 0 (2002)',
        games: ['Resident Evil 0 (2002)', 'Resident Evil (1996 / REmake 2002)', 'Resident Evil: The Umbrella Chronicles (2007)'],
        bio: 'Rebecca Chambers was the youngest member of S.T.A.R.S. Bravo Team, joining at just 18 years old as field medic and biochemistry expert. In July 1998 she was dispatched to the Arklay Mountains where she first encountered Billy Coen aboard a derailed Umbrella training facility, surviving the origins of the T-Virus outbreak orchestrated by James Marcus. Shortly after, she entered the Spencer Mansion as part of the initial investigation, providing medical support to survivors. Her extraordinary intelligence and composure under pressure allowed her to survive both incidents and later contribute to BSAA research efforts.',
    },
    {
        id: 'billy_coen',
        name: 'Billy Coen',
        image: '/images/characters/billy_coen.jpg',
        affiliation: 'U.S. Marines (former)',
        status: 'Unknown',
        firstAppearance: 'Resident Evil 0 (2002)',
        games: ['Resident Evil 0 (2002)'],
        bio: 'Billy Coen is a former U.S. Marine 2nd Lieutenant court-martialed and sentenced to death for the alleged massacre of 23 civilians in Africa — a crime he insists was carried out by his own corrupt unit. His convoy was attacked near Raccoon City in July 1998, allowing him to escape. He teamed up with Rebecca Chambers aboard the infected Umbrella Research Center train and together they defeated the resurrected James Marcus. Rebecca declared him dead so he could live freely; his current whereabouts remain unknown.',
    },
    {
        id: 'james_marcus',
        name: 'James Marcus',
        image: '/images/characters/james_marcus.webp',
        affiliation: 'Umbrella Corporation (founder)',
        status: 'Deceased',
        firstAppearance: 'Resident Evil 0 (2002)',
        games: ['Resident Evil 0 (2002)', 'Resident Evil: The Umbrella Chronicles (2007)'],
        bio: 'Dr. James Marcus was one of three founding members of the Umbrella Corporation. A brilliant virologist, he was the original discoverer of the Progenitor Virus and creator of the first T-Virus strain through leech experiments. In 1978 Spencer had him assassinated; his consciousness was later resurrected through his Leech Queen, driven purely by vengeance. His reborn form unleashed the T-Virus across the Arklay facility in 1998, setting in motion the Raccoon City disaster. He was ultimately destroyed by Rebecca Chambers and Billy Coen.',
    },
    {
        id: 'jill_valentine',
        name: 'Jill Valentine',
        image: '/images/characters/jill_valentine.jpg',
        affiliation: 'S.T.A.R.S. / BSAA',
        status: 'Alive',
        firstAppearance: 'Resident Evil (1996)',
        games: ['Resident Evil (1996 / REmake 2002)', 'Resident Evil 3: Nemesis (1999 / Remake 2020)', 'Resident Evil: The Umbrella Chronicles (2007)', 'Resident Evil 5 (2009)'],
        bio: 'Jill Valentine is a former U.S. Army Delta Force operative and co-founder of the BSAA. As a S.T.A.R.S. Alpha Team member she uncovered Umbrella\'s bioweapons program during the Spencer Mansion incident in 1998, then survived Raccoon City\'s destruction at the hands of Nemesis before the city was nuked. In 2009 she sacrificed herself to save Chris Redfield from Wesker, was captured, infected with Uroboros, and brainwashed before being rescued. She is widely regarded as one of the most capable bioterrorism agents in the world.',
    },
    {
        id: 'chris_redfield',
        name: 'Chris Redfield',
        image: '/images/characters/chris_redfield.webp',
        affiliation: 'S.T.A.R.S. / BSAA',
        status: 'Alive',
        firstAppearance: 'Resident Evil (1996)',
        games: ['Resident Evil (1996 / REmake 2002)', 'Resident Evil Code: Veronica (2000)', 'Resident Evil: The Umbrella Chronicles (2007)', 'Resident Evil 5 (2009)', 'Resident Evil 6 (2012)', 'Resident Evil 7: Biohazard (2017)', 'Resident Evil Village (2021)'],
        bio: 'Chris Redfield is a former U.S. Air Force pilot turned S.T.A.R.S. Alpha Team captain and one of the most decorated bioterrorism operatives in history. He survived the Spencer Mansion incident, rescued his sister Claire in Antarctica, and co-founded the BSAA. His decade-long vendetta against Albert Wesker ended in their volcanic confrontation in Africa in 2009. He later combated the C-Virus outbreak in China and the Village crisis in Eastern Europe, personally pursuing threats connected to the Connections and the Winters family. Scarred by years of war, Chris remains one of the last true veterans of the anti-Umbrella struggle.',
    },
    {
        id: 'barry_burton',
        name: 'Barry Burton',
        image: '/images/characters/barry_burton.webp',
        affiliation: 'S.T.A.R.S. / BSAA (consultant)',
        status: 'Alive',
        firstAppearance: 'Resident Evil (1996)',
        games: ['Resident Evil (1996 / REmake 2002)', 'Resident Evil: Revelations 2 (2015)'],
        bio: 'Barry Burton was the weapons expert of S.T.A.R.S. Alpha Team, known for his enormous .44 Magnum and loyalty to his comrades. During the Spencer Mansion incident he was coerced by Wesker into betraying the team under threat to his family — a choice he overcame, ultimately turning against Wesker and helping Jill survive. After Umbrella\'s fall, he worked as a weapons consultant in Canada. Years later he traveled alone to Sushestvovanie Island to rescue his abducted daughter Moira, forging an alliance with the mysterious child Natalia Korda to dismantle Alex Wesker\'s experiments.',
    },
    {
        id: 'albert_wesker',
        name: 'Albert Wesker',
        image: '/images/characters/albert_wesker.webp',
        affiliation: 'Umbrella Corporation / Tricell / Himself',
        status: 'Deceased',
        firstAppearance: 'Resident Evil (1996)',
        games: ['Resident Evil (1996 / REmake 2002)', 'Resident Evil Code: Veronica (2000)', 'Resident Evil: The Umbrella Chronicles (2007)', 'Resident Evil 5 (2009)'],
        bio: 'Albert Wesker is the primary antagonist of the series — a cold genius raised as one of Spencer\'s "Wesker Children" and indoctrinated from birth to be a superior human. As S.T.A.R.S. captain he secretly worked for Umbrella, using his own team as test subjects. He faked his death during the Mansion incident by injecting a prototype virus, gaining superhuman abilities. He spent years accumulating power before executing his Uroboros Plan — a scheme to release a global bioweapon and force humanity to evolve. He was killed by Chris Redfield and Sheva Alomar when they launched missiles into a volcanic crater in Africa in 2009.',
    },
    {
        id: 'ozwell_spencer',
        name: 'Ozwell E. Spencer',
        image: '/images/characters/ozwell_spencer.webp',
        affiliation: 'Umbrella Corporation (founder)',
        status: 'Deceased',
        firstAppearance: 'Resident Evil 5 (2009)',
        games: ['Resident Evil 5 (2009)'],
        bio: 'Ozwell E. Spencer was the primary founder and CEO of the Umbrella Corporation — a man of immense wealth and a god complex bordering on madness. He co-discovered the Progenitor Virus in Africa and used it as the cornerstone of Umbrella\'s bioweapons research. Driven by the belief that humanity needed to be evolved and that he should be its god, he orchestrated the Wesker Children program — orphans trained to become superhumans who could inherit his new world. Elderly and frail by 2006, he was killed by Albert Wesker himself before he could be interrogated.',
    },
    {
        id: 'richard_aiken',
        name: 'Richard Aiken',
        image: '/images/characters/richard_aiken.webp',
        affiliation: 'S.T.A.R.S.',
        status: 'Deceased',
        firstAppearance: 'Resident Evil (1996)',
        games: ['Resident Evil (1996 / REmake 2002)'],
        bio: 'Richard Aiken was S.T.A.R.S. Alpha Team\'s radio and communications specialist, known for his cheerful personality and loyalty. He was one of the first casualties of the Spencer Mansion incident, bitten by the giant mutant snake Yawn while protecting fellow member Enrico Marini. Despite being gravely poisoned, he held on long enough to warn other survivors and ultimately sacrificed himself to save Chris or Jill from a second serpent attack. His death was a painful early reminder of the dangers lurking within the Spencer Estate.',
    },
    {
        id: 'enrico_marini',
        name: 'Enrico Marini',
        image: '/images/characters/enrico_marini.webp',
        affiliation: 'S.T.A.R.S.',
        status: 'Deceased',
        firstAppearance: 'Resident Evil (1996)',
        games: ['Resident Evil (1996 / REmake 2002)'],
        bio: 'Enrico Marini was the captain of S.T.A.R.S. Bravo Team — the first unit sent to investigate the Arklay Mountain disappearances. A skilled and dedicated leader, he survived deeper into the Spencer Mansion than most of his team and eventually uncovered evidence that a traitor within S.T.A.R.S. was feeding information to Umbrella. He was killed before he could reveal the traitor\'s identity — shot by the traitor himself, Albert Wesker — in the mansion\'s underground tunnels.',
    },
    {
        id: 'leon_kennedy',
        name: 'Leon S. Kennedy',
        image: '/images/characters/leon_kennedy.jpg',
        affiliation: 'RPD (former) / U.S. Government / DSO',
        status: 'Alive',
        firstAppearance: 'Resident Evil 2 (1998)',
        games: ['Resident Evil 2 (1998 / Remake 2019)', 'Resident Evil 4 (2005 / Remake 2023)', 'Resident Evil 6 (2012)', 'Resident Evil: Damnation (2012)', 'Resident Evil: Vendetta (2017)'],
        bio: 'Leon Scott Kennedy arrived in Raccoon City on September 29, 1998 for his first day as an R.P.D. officer, only to find the city overrun by the undead. His survival alongside Claire Redfield and his encounter with Ada Wong forged him into one of the world\'s most skilled agents. Recruited into a secret government program, he spent six years as special forces before rescuing the President\'s daughter Ashley Graham in rural Spain — a mission that exposed the Las Plagas bioweapon threat. He later combated global bioterrorism under direct presidential orders, crossing paths with Ada Wong and old enemies throughout his career.',
    },
    {
        id: 'claire_redfield',
        name: 'Claire Redfield',
        image: '/images/characters/claire_redfield.jpg',
        affiliation: 'TerraSave (NGO)',
        status: 'Alive',
        firstAppearance: 'Resident Evil 2 (1998)',
        games: ['Resident Evil 2 (1998 / Remake 2019)', 'Resident Evil Code: Veronica (2000)', 'Resident Evil: Revelations 2 (2015)'],
        bio: 'Claire Redfield is Chris Redfield\'s younger sister — a college student who rode into Raccoon City looking for her brother and ended up fighting for her life through a zombie apocalypse. She formed a powerful bond with Sherry Birkin, protecting her through the nightmare beneath the city\'s sewers. After escaping, she traveled to Rockfort Island in search of Chris, facing Alexia Ashford and the death of Steve Burnside. In later years she joined the humanitarian NGO TerraSave, where her advocacy work led her to Sushestvovanie Island and another confrontation with bioterrorism.',
    },
    {
        id: 'ada_wong',
        name: 'Ada Wong',
        image: '/images/characters/ada_wong.png',
        affiliation: 'Unknown (various organizations)',
        status: 'Alive',
        firstAppearance: 'Resident Evil 2 (1998)',
        games: ['Resident Evil 2 (1998 / Remake 2019)', 'Resident Evil 4 (2005 / Remake 2023)', 'Resident Evil 6 (2012)'],
        bio: 'Ada Wong is an enigmatic spy whose true loyalties and even her real name remain unknown. She first appeared in Raccoon City posing as a journalist, secretly retrieving a G-Virus sample while developing genuine feelings for Leon Kennedy. She resurfaced in Spain during Leon\'s mission, working multiple agendas simultaneously. During the C-Virus crisis a body double named Carla Radames — surgically altered to look exactly like her — conducted atrocities in her name, forcing Ada to clean up a mess not of her making. Her motivations remain perpetually shrouded in mystery.',
    },
    {
        id: 'sherry_birkin',
        name: 'Sherry Birkin',
        image: '/images/characters/sherry_birkin.webp',
        affiliation: 'U.S. Government / DSO',
        status: 'Alive',
        firstAppearance: 'Resident Evil 2 (1998)',
        games: ['Resident Evil 2 (1998 / Remake 2019)', 'Resident Evil 6 (2012)'],
        bio: 'Sherry Birkin is the daughter of Umbrella researchers William and Annette Birkin, who spent her childhood alone while her parents obsessed over their work. During the Raccoon City outbreak she was infected with the G-Virus by her own mutating father and only survived because Claire administered an incomplete vaccine. The U.S. government took her into custody, using her immunity as a research asset. She grew up under constant government supervision and eventually became a DSO agent, partnering with Jake Muller during the C-Virus crisis — her enhanced healing abilities proving instrumental in developing a vaccine.',
    },
    {
        id: 'william_birkin',
        name: 'William Birkin',
        image: '/images/characters/william_birkin.webp',
        affiliation: 'Umbrella Corporation',
        status: 'Deceased',
        firstAppearance: 'Resident Evil 2 (1998)',
        games: ['Resident Evil 2 (1998 / Remake 2019)'],
        bio: 'Dr. William Birkin was Umbrella\'s most brilliant virologist, creator of the G-Virus — a parasite capable of completely rewriting a host\'s genetic structure to enable radical mutation and regeneration. Having devoted his life to Umbrella\'s research while neglecting his family, he was shot by Umbrella forces when he refused to surrender his G-Virus samples. He injected himself with the virus to survive, transforming into a grotesque ever-mutating creature driven by primal instinct. His rampage through Raccoon City\'s sewers and underground labs contributed massively to the city\'s downfall, and his scattered G-Virus inadvertently infected his own daughter Sherry.',
    },
    {
        id: 'annette_birkin',
        name: 'Annette Birkin',
        image: '/images/characters/annette_birkin.jpg',
        affiliation: 'Umbrella Corporation',
        status: 'Deceased',
        firstAppearance: 'Resident Evil 2 (1998)',
        games: ['Resident Evil 2 (1998 / Remake 2019)'],
        bio: 'Annette Birkin was a senior Umbrella researcher who co-developed the G-Virus alongside her husband William, sacrificing her role as a mother in service to their shared obsession. Cold and calculating on the surface, she initially hindered Leon and Claire\'s progress out of paranoia and a desperate need to protect her husband\'s research. However, her love for her daughter Sherry ultimately prevailed — she provided Claire with the antidote formula for the G-Virus and sacrificed her own life to help them escape, dying from injuries sustained by a mutated William in what were her most genuinely human moments.',
    },
    {
        id: 'hunk',
        name: 'HUNK',
        image: '/images/characters/hunk.jpg',
        affiliation: 'Umbrella Corporation (U.S.S.)',
        status: 'Unknown',
        firstAppearance: 'Resident Evil 2 (1998)',
        games: ['Resident Evil 2 (1998 / Remake 2019)', 'Resident Evil 4 — The Mercenaries', 'Resident Evil 6 — The Mercenaries'],
        bio: 'HUNK is the legendary Umbrella Security Service operative known as the "Grim Reaper" — a moniker earned because he is invariably the only member of his team to ever survive a mission. He was sent to Raccoon City to recover a G-Virus sample from William Birkin; despite losing his entire squad, he completed the objective and escaped the doomed city against all odds. His real name, history, and face remain classified. His survival instinct is so refined he seems almost inhuman, cementing his status as an iconic and near-mythical figure in the RE universe.',
    },
    {
        id: 'brian_irons',
        name: 'Brian Irons',
        image: '/images/characters/brian_irons.jpg',
        affiliation: 'Raccoon City Police Department',
        status: 'Deceased',
        firstAppearance: 'Resident Evil 2 (1998)',
        games: ['Resident Evil 2 (1998 / Remake 2019)'],
        bio: 'Brian Irons was the deeply corrupt chief of the Raccoon City Police Department, on Umbrella\'s payroll for years and suppressing investigations into the corporation. A violent and unstable man with a criminal past Umbrella helped cover up, he actively sabotaged evacuation efforts during the zombie outbreak to prevent survivors from testifying. Obsessed with taxidermy, he attempted to use Claire Redfield\'s body for his collection before being killed by a G-embryo implanted in him by William Birkin — a deeply ironic end for one of Umbrella\'s most loyal human tools.',
    },
    {
        id: 'marvin_branagh',
        name: 'Marvin Branagh',
        image: '/images/characters/marvin_branagh.jpg',
        affiliation: 'Raccoon City Police Department',
        status: 'Deceased',
        firstAppearance: 'Resident Evil 2 (1998)',
        games: ['Resident Evil 2 (1998 / Remake 2019)'],
        bio: 'Marvin Branagh was an R.P.D. lieutenant and one of the few genuinely good officers in a department riddled with corruption. During the initial outbreak he rallied survivors inside the police station and fought until a zombie bite sapped his strength. Despite being infected and slowly turning, he held on long enough to unlock the way forward for both Leon and Claire, refusing to give up while there was still a chance to help others. His struggle against the infection and his final moments of fully succumbing remain among the most poignant scenes in the series.',
    },
    {
        id: 'carlos_oliveira',
        name: 'Carlos Oliveira',
        image: '/images/characters/carlos_oliveira.jpg',
        affiliation: 'UBCS',
        status: 'Alive',
        firstAppearance: 'Resident Evil 3: Nemesis (1999)',
        games: ['Resident Evil 3: Nemesis (1999)', 'Resident Evil 3 Remake (2020)'],
        bio: 'Carlos Oliveira was a mercenary recruited by Umbrella\'s UBCS — a unit deployed into Raccoon City as cannon fodder to gather combat data on T-Virus zombies. A former Latin American guerrilla fighter with natural charm and real combat skills, Carlos developed a genuine desire to help when he encountered Jill Valentine. He administered a vaccine that saved her life after a Nemesis attack and proved instrumental in helping her escape the doomed city. One of the few UBCS members to survive with both life and conscience intact, Carlos represents the human capacity to choose good even when employed by evil.',
    },
    {
        id: 'mikhail_victor',
        name: 'Mikhail Victor',
        image: '/images/characters/mikhail_victor.jpg',
        affiliation: 'UBCS',
        status: 'Deceased',
        firstAppearance: 'Resident Evil 3: Nemesis (1999)',
        games: ['Resident Evil 3: Nemesis (1999)', 'Resident Evil 3 Remake (2020)'],
        bio: 'Mikhail Victor was a UBCS sergeant and leader of a small group of survivors attempting to escape Raccoon City aboard a tram. Already critically wounded when Jill Valentine encountered him, Mikhail was too injured to fight but refused to abandon his people. In his final act of heroism he sacrificed himself by detonating a grenade against the Nemesis — buying enough time for the tram to carry survivors to safety. A tragic figure representing the soldiers used and discarded by Umbrella in its desperate bid to cover its tracks.',
    },
    {
        id: 'nikolai_zinoviev',
        name: 'Nikolai Zinoviev',
        image: '/images/characters/nikolai_zinoviev.jpg',
        affiliation: 'UBCS / Umbrella (spy)',
        status: 'Unknown',
        firstAppearance: 'Resident Evil 3: Nemesis (1999)',
        games: ['Resident Evil 3: Nemesis (1999)', 'Resident Evil 3 Remake (2020)'],
        bio: 'Nikolai Zinoviev appeared to be a seasoned UBCS sergeant but was in reality a "Monitor" — a spy embedded within the unit to collect combat data on B.O.W.s and eliminate witnesses who knew too much, including his own teammates. Cold, professional, and utterly mercenary, his only loyalty was to whoever paid the most. He engineered the deaths of multiple UBCS operatives and actively antagonized Jill Valentine. He escaped the doomed city having sold Umbrella\'s data to the highest bidder — a true survivor with no conscience.',
    },
    {
        id: 'steve_burnside',
        name: 'Steve Burnside',
        image: '/images/characters/steve_burnside.jpg',
        affiliation: 'None',
        status: 'Deceased',
        firstAppearance: 'Resident Evil Code: Veronica (2000)',
        games: ['Resident Evil Code: Veronica (2000)'],
        bio: 'Steve Burnside was a young prisoner on Rockfort Island whose father had sold classified information to Umbrella. When Claire Redfield arrived during a raid, he initially distrusted her but the two bonded as they fought to survive the zombie outbreak. Brash and emotionally troubled, Steve was nonetheless capable of great courage and genuine affection for Claire. He was captured and injected with the T-Veronica Virus by Alexia Ashford, transforming into a monstrous creature — yet managed to overcome the mutation just long enough to protect Claire before succumbing and dying in her arms.',
    },
    {
        id: 'alexia_ashford',
        name: 'Alexia Ashford',
        image: '/images/characters/alexia_ashford.jpg',
        affiliation: 'Umbrella Corporation',
        status: 'Deceased',
        firstAppearance: 'Resident Evil Code: Veronica (2000)',
        games: ['Resident Evil Code: Veronica (2000)'],
        bio: 'Alexia Ashford was the prodigious granddaughter of Umbrella founder Edward Ashford — a genius who earned her doctorate at age ten. Obsessed with power and perfection, she spent years in cryogenic stasis after injecting herself with the T-Veronica Virus, allowing it to bond slowly with her DNA. She emerged 15 years later with the ability to control insects, generate fire, and transform into increasingly monstrous forms. Supremely arrogant and cruel, she viewed other humans as insects beneath her. She was defeated by Chris Redfield in Antarctica, though not before leaving a trail of devastation across Rockfort Island and the southern continent.',
    },
    {
        id: 'alfred_ashford',
        name: 'Alfred Ashford',
        image: '/images/characters/alfred_ashford.jpg',
        affiliation: 'Umbrella Corporation',
        status: 'Deceased',
        firstAppearance: 'Resident Evil Code: Veronica (2000)',
        games: ['Resident Evil Code: Veronica (2000)'],
        bio: 'Alfred Ashford was Alexia\'s twin brother — a mediocre individual who lived entirely in his sister\'s shadow, consumed by jealousy over her brilliance. He commanded Rockfort Island on behalf of Umbrella but was driven to severe mental instability by his obsession with Alexia and grief over her apparent death. So shattered was his psyche that he developed a split personality, sometimes dressing and acting as Alexia herself. He pursued Claire and Steve with fanatical determination and eventually died from wounds sustained in an aircraft, his last act being to wake Alexia from her long slumber.',
    },
    {
        id: 'ashley_graham',
        name: 'Ashley Graham',
        image: '/images/characters/ashley_graham.jpg',
        affiliation: 'U.S. Government (President\'s daughter)',
        status: 'Alive',
        firstAppearance: 'Resident Evil 4 (2005)',
        games: ['Resident Evil 4 (2005 / Remake 2023)'],
        bio: 'Ashley Graham is the daughter of the U.S. President, kidnapped by the Los Illuminados cult to be implanted with Las Plagas and used as a biological weapon against the government. Despite being portrayed primarily as a rescue target, Ashley demonstrated significant courage and resourcefulness throughout her captivity, actively aiding Leon Kennedy in their mutual survival. The two succeeded in removing the Las Plagas organisms using an experimental device. In the remake she is portrayed with greater agency and inner strength, displaying real determination rather than passive helplessness.',
    },
    {
        id: 'luis_sera',
        name: 'Luis Sera',
        image: '/images/characters/luis_sera.jpg',
        affiliation: 'Los Illuminados (former) / independent',
        status: 'Deceased',
        firstAppearance: 'Resident Evil 4 (2005)',
        games: ['Resident Evil 4 (2005 / Remake 2023)'],
        bio: 'Luis Sera was a former Madrid police officer recruited by the Los Illuminados cult as a researcher studying Las Plagas. Having grown disillusioned with their extremism, he secretly contacted Ada Wong with the intention of stealing the dominant Plaga sample for Wesker. Charming, witty, and perpetually casual despite mortal danger around him, Luis formed a genuine bond with Leon during their brief captivity and provided crucial assistance including a suppressant for their Plaga infections. He was killed by Saddler before he could complete his mission — his death remaining one of RE4\'s most unexpected and impactful moments.',
    },
    {
        id: 'jack_krauser',
        name: 'Jack Krauser',
        image: '/images/characters/jack_krauser.jpg',
        affiliation: 'U.S. Special Forces (former) / Wesker / Los Illuminados',
        status: 'Deceased',
        firstAppearance: 'Resident Evil 4 (2005)',
        games: ['Resident Evil 4 (2005 / Remake 2023)'],
        bio: 'Jack Krauser was a former U.S. Special Forces operative who worked alongside Leon Kennedy on a classified mission in 2002, where a catastrophic injury forced his early retirement. Embittered and desperate to remain relevant, he entered a covert deal with Albert Wesker — in exchange for Plaga samples that could restore and enhance his capabilities, he would conduct intelligence operations and infiltrate the Los Illuminados cult. His arm mutated by the Plaga into a deadly bio-weapon, Krauser became Saddler\'s right hand while secretly pursuing Wesker\'s agenda. His final battle with Leon was deeply personal — a brutal fight between former allies that ended with Krauser\'s death.',
    },
    {
        id: 'osmund_saddler',
        name: 'Osmund Saddler',
        image: '/images/characters/osmund_saddler.jpg',
        affiliation: 'Los Illuminados',
        status: 'Deceased',
        firstAppearance: 'Resident Evil 4 (2005)',
        games: ['Resident Evil 4 (2005 / Remake 2023)'],
        bio: 'Lord Osmund Saddler was the charismatic and megalomaniacal leader of the Los Illuminados, a cult that discovered Las Plagas — an ancient mind-controlling parasite — buried beneath a Spanish village. Using the Plaga to enslave the local population, Saddler planned to infect key figures in the U.S. government to destabilize the country. Cunning and supremely confident in his Plaga-enhanced power, he effortlessly saw through the schemes of both Krauser and Ada Wong while using them as tools. He transformed into a monstrous creature during his final battle with Leon, who destroyed him with Ada\'s Rocket Launcher.',
    },
    {
        id: 'ingrid_hunnigan',
        name: 'Ingrid Hunnigan',
        image: '/images/characters/ingrid_hunnigan.jpg',
        affiliation: 'U.S. Government',
        status: 'Alive',
        firstAppearance: 'Resident Evil 4 (2005)',
        games: ['Resident Evil 4 (2005 / Remake 2023)', 'Resident Evil 6 (2012)', 'Resident Evil: Damnation (2012)'],
        bio: 'Ingrid Hunnigan is a government field analyst and Leon Kennedy\'s primary mission control operator, providing intelligence and tactical support across multiple operations. Professional, sharp, and unfailingly composed under pressure, she maintains contact with Leon through some of the most communication-hostile environments imaginable. During Leon\'s mission in Spain, Saddler\'s forces jammed her signal and briefly took her offline — highlighting just how essential she is to his operations. Her dry wit and steady professionalism provide an effective counterpoint to Leon\'s more brooding demeanor.',
    },
    {
        id: 'the_merchant',
        name: 'The Merchant',
        image: '/images/characters/the_merchant.jpg',
        affiliation: 'Unknown',
        status: 'Unknown',
        firstAppearance: 'Resident Evil 4 (2005)',
        games: ['Resident Evil 4 (2005 / Remake 2023)'],
        bio: 'The Merchant is one of the most iconic and mysterious figures in the RE universe — a hooded arms dealer of unknown origin who appears throughout rural Spain and Salazar Castle, somehow always one step ahead of Leon and always willing to trade. His catchphrase — "What\'re ya buyin\'?" — has become permanently embedded in gaming culture. Despite being infected with Las Plagas himself, he maintains his personality and independence, suggesting unique resistance or a special relationship with the parasite. In the remake he wears a welding mask and hints at a tragic past without ever revealing his true identity.',
    },
    {
        id: 'sheva_alomar',
        name: 'Sheva Alomar',
        image: '/images/characters/sheva_alomar.jpg',
        affiliation: 'BSAA (West African Branch)',
        status: 'Alive',
        firstAppearance: 'Resident Evil 5 (2009)',
        games: ['Resident Evil 5 (2009)'],
        bio: 'Sheva Alomar is a BSAA West African Branch operative who partnered with Chris Redfield during an investigation into a bio-weapons deal in the Kijuju Autonomous Zone. Born in West Africa, she watched Umbrella test its bio-weapons on her village as a child — an experience that fueled her determination to join the BSAA. Highly skilled in combat and deeply committed to protecting her homeland, Sheva proved to be an equal partner to the veteran Chris throughout the operation. Together they uncovered Wesker\'s global Uroboros plan and put a permanent end to his decades-long threat.',
    },
    {
        id: 'excella_gionne',
        name: 'Excella Gionne',
        image: '/images/characters/excella_gionne.jpg',
        affiliation: 'Tricell / Wesker',
        status: 'Deceased',
        firstAppearance: 'Resident Evil 5 (2009)',
        games: ['Resident Evil 5 (2009)'],
        bio: 'Excella Gionne was the CEO of Tricell\'s pharmaceutical division in Africa and Albert Wesker\'s primary collaborator in executing the Uroboros Project. An aristocratic woman of great intelligence and ambition, she was utterly devoted to Wesker — believing he would make her his equal in a new world of evolved humanity. In reality Wesker viewed her as a useful tool and never intended to honor their arrangement. She was betrayed when Wesker infected her with Uroboros, causing her to mutate into a monstrous creature that Chris and Sheva were forced to destroy. Her blind faith in Wesker\'s promises proved to be her undoing.',
    },
    {
        id: 'josh_stone',
        name: 'Josh Stone',
        image: '/images/characters/josh_stone.jpg',
        affiliation: 'BSAA (West African Branch)',
        status: 'Alive',
        firstAppearance: 'Resident Evil 5 (2009)',
        games: ['Resident Evil 5 (2009)'],
        bio: 'Josh Stone was Sheva Alomar\'s mentor and captain of the BSAA West African Branch, who recruited and trained her after her village was targeted by Umbrella. A seasoned and reliable operative, he coordinated the broader mission in Kijuju from the field while Chris and Sheva pushed deeper into the infected zone. When contact was lost, he mounted a personal rescue mission and provided the helicopter extraction that saved Chris and Sheva during their final confrontation with Wesker. His unshakeable composure and loyalty to his team make him one of the series\' most dependable supporting characters.',
    },
    {
        id: 'parker_luciani',
        name: 'Parker Luciani',
        image: '/images/characters/parker_luciani.jpg',
        affiliation: 'BSAA',
        status: 'Alive',
        firstAppearance: 'Resident Evil: Revelations (2012)',
        games: ['Resident Evil: Revelations (2012)'],
        bio: 'Parker Luciani is a BSAA agent who partnered with Jill Valentine during an operation aboard the cruise ship Queen Zenobia in the Mediterranean Sea. Easygoing and good-humored on the surface, Parker concealed a traumatic past: he was forced to shoot his own partner during an operation gone wrong, and later discovered he had been manipulated by the criminal organization Il Veltro. His loyalty and capacity for self-sacrifice — demonstrated when he bought Jill time to escape at great personal cost — define his character. He ultimately survived the ordeal, though barely.',
    },
    {
        id: 'jessica_sherawat',
        name: 'Jessica Sherawat',
        image: '/images/characters/jessica_sherawat.jpg',
        affiliation: 'BSAA / Tricell (secretly)',
        status: 'Unknown',
        firstAppearance: 'Resident Evil: Revelations (2012)',
        games: ['Resident Evil: Revelations (2012)'],
        bio: 'Jessica Sherawat appeared to be a capable BSAA agent partnered with Chris Redfield, but was later revealed to be a double agent working for Tricell and other organizations. She used her position to steal the T-Abyss Virus sample and escape amid the chaos of the Queen Zenobia operation, betraying both Chris and Parker without hesitation. Her casual cruelty and willingness to sacrifice teammates for personal gain made her one of the more despised traitors in the series. Her whereabouts after escaping remain unknown.',
    },
    {
        id: 'jake_muller',
        name: 'Jake Muller',
        image: '/images/characters/jake_muller.jpg',
        affiliation: 'Independent / BSAA (consultant)',
        status: 'Alive',
        firstAppearance: 'Resident Evil 6 (2012)',
        games: ['Resident Evil 6 (2012)'],
        bio: 'Jake Muller is the illegitimate son of Albert Wesker, raised in poverty in Eastern Europe with no knowledge of his father\'s identity. He worked as a mercenary to survive. His unique genetic inheritance — a natural immunity to the C-Virus — made him the most important person on the planet during the C-Virus crisis, as his blood was the key to synthesizing a vaccine. Initially motivated purely by money, his partnership with Sherry Birkin gradually awakened a sense of purpose and responsibility. He inherited Wesker\'s superhuman physical capabilities without inheriting his megalomaniacal worldview — making him one of the more hopeful figures in the series.',
    },
    {
        id: 'piers_nivans',
        name: 'Piers Nivans',
        image: '/images/characters/piers_nivans.jpg',
        affiliation: 'BSAA (Alpha Team)',
        status: 'Deceased',
        firstAppearance: 'Resident Evil 6 (2012)',
        games: ['Resident Evil 6 (2012)'],
        bio: 'Piers Nivans was the star sharpshooter of BSAA Alpha Team and Chris Redfield\'s most trusted subordinate — a gifted soldier who idolized Chris and believed deeply in the BSAA\'s mission. When Chris suffered a complete mental breakdown following a devastating ambush, Piers spent six months tracking him down and convincing him to return to duty. During their final mission in Lanshiang, Piers injected himself with a C-Virus enhanced strain to save Chris from a mutated Haos creature, gaining a bio-weapon arm but sacrificing his humanity. He forced Chris into an escape pod and died alone as the facility collapsed — his sacrifice ensuring Chris\'s survival.',
    },
    {
        id: 'helena_harper',
        name: 'Helena Harper',
        image: '/images/characters/helena_harper.jpg',
        affiliation: 'U.S. Secret Service / DSO',
        status: 'Alive',
        firstAppearance: 'Resident Evil 6 (2012)',
        games: ['Resident Evil 6 (2012)'],
        bio: 'Helena Harper was a U.S. Secret Service agent assigned to protect President Adam Benford, forced to assist in his assassination after her sister Deborah was kidnapped and used as leverage by Derek Simmons. Consumed by guilt and desperate to expose Simmons\'s crimes, she partnered with Leon Kennedy to unravel the truth behind the global C-Virus attack. Her sister was ultimately transformed into a B.O.W. by the C-Virus, forcing Helena to destroy her — the defining tragedy that drove her throughout the game. After clearing her name she transferred to the Division of Security Operations alongside Leon.',
    },
    {
        id: 'derek_simmons',
        name: 'Derek C. Simmons',
        image: '/images/characters/derek_simmons.jpg',
        affiliation: 'U.S. Government / The Family',
        status: 'Deceased',
        firstAppearance: 'Resident Evil 6 (2012)',
        games: ['Resident Evil 6 (2012)'],
        bio: 'Derek C. Simmons was the U.S. National Security Advisor and secret leader of The Family — an ancient organization dedicated to maintaining world stability through clandestine control. Brilliant and ruthless, he orchestrated the creation of the C-Virus and global bioterrorism attacks as part of a personal vendetta against Ada Wong, who had rejected his obsessive love. He had his researcher Carla Radames surgically transformed into an Ada lookalike — a plan that backfired catastrophically. Infected multiple times by different B.O.W.s during his final confrontation with Leon, he refused to die until Leon put him down permanently.',
    },
    {
        id: 'carla_radames',
        name: 'Carla Radames',
        image: '/images/characters/carla_radames.jpg',
        affiliation: 'The Family / Neo-Umbrella',
        status: 'Deceased',
        firstAppearance: 'Resident Evil 6 (2012)',
        games: ['Resident Evil 6 (2012)'],
        bio: 'Carla Radames was a brilliant virologist who worked for Derek Simmons and developed the C-Virus — only to be forcibly transformed by Simmons into an exact physical replica of Ada Wong using her own creation. Her original identity destroyed and replaced, the new "Ada" was consumed by hatred for Simmons and sought to destroy him by triggering a global pandemic. She founded Neo-Umbrella as a vehicle for her vengeance, conducting bioterrorism on a massive scale. Carla was ultimately killed by Simmons\'s agents before completing her plan, while the real Ada struggled to distance herself from the chaos carried out in her name.',
    },
    {
        id: 'moira_burton',
        name: 'Moira Burton',
        image: '/images/characters/moira_burton.jpg',
        affiliation: 'TerraSave / BSAA (consultant)',
        status: 'Alive',
        firstAppearance: 'Resident Evil: Revelations 2 (2015)',
        games: ['Resident Evil: Revelations 2 (2015)'],
        bio: 'Moira Burton is Barry Burton\'s daughter and a TerraSave employee who was abducted alongside Claire Redfield and taken to Sushestvovanie Island as a test subject for Alex Wesker\'s fear experiments. Skilled and intelligent, Moira struggles with a debilitating fear of firearms stemming from a childhood accident involving her father\'s gun — compensating with a crowbar and flashlight. Her strained relationship with her father is a central emotional thread of the game, culminating in a powerful reunion that forces both to confront their shared guilt and find reconciliation.',
    },
    {
        id: 'natalia_korda',
        name: 'Natalia Korda',
        image: '/images/characters/natalia_korda.jpg',
        affiliation: 'Unknown',
        status: 'Alive (with caveats)',
        firstAppearance: 'Resident Evil: Revelations 2 (2015)',
        games: ['Resident Evil: Revelations 2 (2015)'],
        bio: 'Natalia Korda is a mysterious young girl found on Sushestvovanie Island who possesses an uncanny ability to sense the presence and emotional state of nearby creatures — a power invaluable to Barry Burton during their partnership on the island. Quiet and eerily calm, she survived the island\'s horrors without weapons of any kind. The disturbing twist: Alex Wesker had secretly copied her consciousness into Natalia\'s body, intending to use the child as a vessel for her own survival. The question of who — or what — truly inhabits Natalia at the story\'s end remains one of the series\' most unsettling conclusions.',
    },
    {
        id: 'alex_wesker',
        name: 'Alex Wesker',
        image: '/images/characters/alex_wesker.jpg',
        affiliation: 'Umbrella Corporation (former) / Herself',
        status: 'Deceased (presumably)',
        firstAppearance: 'Resident Evil: Revelations 2 (2015)',
        games: ['Resident Evil 5 (2009) — mentioned in files', 'Resident Evil: Revelations 2 (2015)'],
        bio: 'Alex Wesker was one of the original Wesker Children — the survivors of Spencer\'s eugenics program — entrusted by Spencer to achieve immortality and carry his legacy. Unlike Albert, Alex pursued immortality through consciousness transfer technology. She spent years on Sushestvovanie Island conducting fear experiments on prisoners to develop her methodology, ultimately transferring her mind into the child Natalia Korda. However, the original Alex\'s body rejected the test virus, driving her increasingly insane before her physical form was destroyed in a confrontation with Barry Burton and Natalia.',
    },
    {
        id: 'neil_fisher',
        name: 'Neil Fisher',
        image: '/images/characters/neil_fisher.jpg',
        affiliation: 'TerraSave / Alex Wesker (secretly)',
        status: 'Deceased',
        firstAppearance: 'Resident Evil: Revelations 2 (2015)',
        games: ['Resident Evil: Revelations 2 (2015)'],
        bio: 'Neil Fisher was a high-ranking TerraSave official and apparent ally who organized the abduction of TerraSave members to Sushestvovanie Island on behalf of Alex Wesker — motivated by the promise of a virus that could cure his terminal illness. His betrayal of Claire and his colleagues made him one of the more personally felt antagonists of Revelations 2. He was infected with an Uroboros strain by Alex Wesker and transformed into a massive B.O.W. that Claire was forced to destroy — a fate he brought entirely upon himself through his desperate choices.',
    },
    {
        id: 'ethan_winters',
        name: 'Ethan Winters',
        image: '/images/characters/ethan_winters.jpg',
        affiliation: 'None / BSAA',
        status: 'Deceased',
        firstAppearance: 'Resident Evil 7: Biohazard (2017)',
        games: ['Resident Evil 7: Biohazard (2017)', 'Resident Evil Village (2021)'],
        bio: 'Ethan Winters was an ordinary civilian systems engineer who became one of the most extraordinary survivors in RE history — entirely by accident. He traveled to a derelict Louisiana plantation to find his missing wife Mia, only to discover the Baker family had been enslaved by Eveline\'s Mold — a bioweapon that also infected Ethan himself, granting him extraordinary regenerative abilities. After a second nightmare in an Eastern European village, he learned the full truth: he had died in Louisiana and was only "alive" because the Mold had completely replaced his biology. He ultimately sacrificed himself to destroy Mother Miranda and save his daughter Rose.',
    },
    {
        id: 'mia_winters',
        name: 'Mia Winters',
        image: '/images/characters/mia_winters.jpg',
        affiliation: 'The Connections (former)',
        status: 'Alive',
        firstAppearance: 'Resident Evil 7: Biohazard (2017)',
        games: ['Resident Evil 7: Biohazard (2017)', 'Resident Evil Village (2021)'],
        bio: 'Mia Winters presented herself to Ethan as an ordinary woman working in childcare, concealing the truth that she was an operative for the criminal bioweapons organization known as The Connections. She was tasked with transporting Eveline — a self-replicating bioweapon — when the child escaped and infected both Mia and the Baker family. After surviving the events of RE7, she attempted to build a genuine normal life with Ethan and their daughter Rose, though the organization\'s reach eventually found them again during the Village crisis.',
    },
    {
        id: 'jack_baker',
        name: 'Jack Baker',
        image: '/images/characters/jack_baker.jpg',
        affiliation: 'None (enslaved by Mold)',
        status: 'Deceased',
        firstAppearance: 'Resident Evil 7: Biohazard (2017)',
        games: ['Resident Evil 7: Biohazard (2017)'],
        bio: 'Jack Baker was the patriarch of the Baker family — a kind and generous Louisiana farmer before Eveline infected him and his family with the Mold, transforming them into violent, nearly unkillable hosts serving her will. As the Mold consumed more of his humanity, Jack became a terrifying, regenerating pursuer who stalked Ethan relentlessly through the plantation. In his final lucid moments the real Jack emerged — a father desperately trying to protect his family — and he begged Ethan to put an end to the nightmare. His death was ultimately an act of mercy, and one of the game\'s most affecting scenes.',
    },
    {
        id: 'marguerite_baker',
        name: 'Marguerite Baker',
        image: '/images/characters/marguerite_baker.jpg',
        affiliation: 'None (enslaved by Mold)',
        status: 'Deceased',
        firstAppearance: 'Resident Evil 7: Biohazard (2017)',
        games: ['Resident Evil 7: Biohazard (2017)'],
        bio: 'Marguerite Baker was Jack\'s wife and the Baker household\'s hostess — once a warm Southern matriarch, transformed by Eveline\'s Mold into a frenzied, insect-controlling monster. She retained a distorted maternal instinct but directed it toward Eveline rather than her own children, funneling it into homicidal protectiveness. She stalked Ethan through the swampy terrain surrounding the Baker estate, commanding swarms of insects and bursting with grotesque biological growth. Like her husband, the woman she once was had been entirely consumed by Eveline\'s parasitic influence long before Ethan arrived.',
    },
    {
        id: 'lucas_baker',
        name: 'Lucas Baker',
        image: '/images/characters/lucas_baker.jpg',
        affiliation: 'The Connections',
        status: 'Deceased',
        firstAppearance: 'Resident Evil 7: Biohazard (2017)',
        games: ['Resident Evil 7: Biohazard (2017)'],
        bio: 'Lucas Baker was the Bakers\' sadistic son who, unlike the rest of his family, retained his own mind after Eveline\'s infection — a fact he exploited by striking a deal with The Connections for a suppressant that kept Eveline\'s control at bay. Already displaying disturbing psychopathic tendencies before the infection, Lucas embraced his situation as an opportunity for unrestricted cruelty, constructing elaborate deadly traps for victims. He was ultimately hunted down and killed by Chris Redfield and BSAA operatives in a follow-up mission after the main events of RE7.',
    },
    {
        id: 'zoe_baker',
        name: 'Zoe Baker',
        image: '/images/characters/zoe_baker.jpg',
        affiliation: 'None',
        status: 'Alive',
        firstAppearance: 'Resident Evil 7: Biohazard (2017)',
        games: ['Resident Evil 7: Biohazard (2017)'],
        bio: 'Zoe Baker is the Bakers\' daughter — a victim of her own family\'s tragedy who resisted Eveline\'s infection long enough to retain her identity while remaining trapped on the plantation. She secretly guided Ethan through text messages and phone calls, providing crucial information about the Mold and how to fight it. Unlike her parents, Zoe was never fully subsumed — her refusal to give in to despair kept her tethered to herself. Her survival after the events of RE7 depends on player choices, and she is the focus of the "End of Zoe" DLC where her uncle Joe Baker fights to save her.',
    },
    {
        id: 'eveline',
        name: 'Eveline',
        image: '/images/characters/eveline.jpg',
        affiliation: 'The Connections',
        status: 'Deceased',
        firstAppearance: 'Resident Evil 7: Biohazard (2017)',
        games: ['Resident Evil 7: Biohazard (2017)'],
        bio: 'Eveline is a unique genetically engineered bioweapon — a child-shaped E-Series B.O.W. capable of producing and spreading the Mold, a fungal bioweapon that infects and enslaves hosts to her will. Designed to appear as a normal child, she craved a real family with a desperate, consuming need — a desire that became monstrous combined with her powers. After escaping from Mia\'s custody she infected the Baker family to become her "family." Her body aged rapidly and she became a withered old woman before manifesting as a grotesque creature, ultimately destroyed by Ethan using a serum derived from her own cells.',
    },
    {
        id: 'joe_baker',
        name: 'Joe Baker',
        image: '/images/characters/joe_baker.jpg',
        affiliation: 'None',
        status: 'Alive',
        firstAppearance: 'Resident Evil 7 — End of Zoe DLC (2017)',
        games: ['Resident Evil 7: Biohazard — End of Zoe DLC (2017)'],
        bio: 'Joe Baker is Jack Baker\'s brother — a gruff, straight-talking swamp-dweller who lived alone in the bayou and avoided Eveline\'s infection by sheer distance. When Zoe was left comatose after the events of RE7, Joe embarked on a solo mission through the Mold-infested swamps to find a cure, fighting off Molded creatures with his bare fists and improvised weapons. His campaign brought him into direct conflict with a massive Molded creature called the Swamp Man and ultimately into collision with BSAA soldiers. Played entirely as an action DLC, Joe provides a grounded perspective on the Baker family\'s tragedy.',
    },
    {
        id: 'mother_miranda',
        name: 'Mother Miranda',
        image: '/images/characters/mother_miranda.jpg',
        affiliation: 'The Village / Umbrella (indirectly)',
        status: 'Deceased',
        firstAppearance: 'Resident Evil Village (2021)',
        games: ['Resident Evil Village (2021)'],
        bio: 'Mother Miranda was the charismatic and godlike religious leader of an isolated Eastern European village, revered for centuries as a divine figure — a persona maintained through extraordinary longevity granted by the Megamycete, a vast fungal neural network beneath the village. In reality she was a grieving mother who lost her daughter Eva to disease a century prior and spent decades experimenting on the village\'s population. She worked alongside Oswell Spencer in Umbrella\'s earliest days and ultimately abducted Rose Winters in her final attempt to resurrect Eva. Centuries of unchallenged power had long since stripped away her humanity, and she was finally defeated by Ethan Winters.',
    },
    {
        id: 'alcina_dimitrescu',
        name: 'Lady Alcina Dimitrescu',
        image: '/images/characters/alcina_dimitrescu.jpg',
        affiliation: 'Mother Miranda / The Four Lords',
        status: 'Deceased',
        firstAppearance: 'Resident Evil Village (2021)',
        games: ['Resident Evil Village (2021)'],
        bio: 'Lady Alcina Dimitrescu was the imposing 9\'6" aristocratic lord of Castle Dimitrescu — an elegant and terrifying figure who ruled over her castle and three "daughters" with imperial authority. A Cadou parasite host whose unique mutation granted her regeneration, superhuman strength, and an insatiable need to consume human blood, she pursued Ethan through every corridor of her castle with relentless aristocratic disdain before transforming into a winged dragon-like creature in her final battle. Originally a human woman with a rare blood condition that made her susceptible to Miranda\'s experiments, she was transformed over decades into an immortal predator. Her design made her an instant cultural phenomenon.',
    },
    {
        id: 'karl_heisenberg',
        name: 'Karl Heisenberg',
        image: '/images/characters/karl_heisenberg.jpg',
        affiliation: 'Mother Miranda / The Four Lords',
        status: 'Deceased',
        firstAppearance: 'Resident Evil Village (2021)',
        games: ['Resident Evil Village (2021)'],
        bio: 'Karl Heisenberg was the magnetic, eccentric lord of a factory — a Cadou host whose mutation granted him extraordinary electromagnetic powers, allowing him to manipulate metal with his mind. Unlike the other Lords, Heisenberg despised Miranda and had secretly been building an army of mechanical B.O.W.s — the Soldat — in preparation for rebellion. He attempted to recruit Ethan as an ally against Miranda; when Ethan refused, Heisenberg deployed his factory\'s full arsenal against him. He was ultimately destroyed when Chris Redfield intervened with a military railgun vehicle. His sardonic wit and rebellious nature made him an instant fan favorite.',
    },
    {
        id: 'donna_beneviento',
        name: 'Donna Beneviento',
        image: '/images/characters/donna_beneviento.jpg',
        affiliation: 'Mother Miranda / The Four Lords',
        status: 'Deceased',
        firstAppearance: 'Resident Evil Village (2021)',
        games: ['Resident Evil Village (2021)'],
        bio: 'Donna Beneviento was the reclusive and deeply unsettling lord of House Beneviento — a Cadou host who almost never appeared in person, communicating through her porcelain puppet Angie and ruling through the hallucinogenic pollen throughout her domain. Severely antisocial and traumatized by her own appearance, she used her powers to trap Ethan in a nightmarish sequence of hallucinations drawing on his deepest fears, culminating in one of the most terrifying moments in the entire series. Her death sequence, where Angie is destroyed during a surreal game of hide-and-seek, is considered among the game\'s most disturbing encounters.',
    },
    {
        id: 'salvatore_moreau',
        name: 'Salvatore Moreau',
        image: '/images/characters/salvatore_moreau.jpg',
        affiliation: 'Mother Miranda / The Four Lords',
        status: 'Deceased',
        firstAppearance: 'Resident Evil Village (2021)',
        games: ['Resident Evil Village (2021)'],
        bio: 'Salvatore Moreau was the pitiful and grotesque lord presiding over the village\'s reservoir — a Cadou host whose mutation was among the most extreme and physically devastating of the four Lords, transforming him into a massive fish-like creature. Unlike the other Lords, Moreau was fully conscious of his own hideousness and desperately craved Miranda\'s approval and affection, which she withheld while using him as a tool. Pathetic but dangerous, his fish form was capable of swallowing Ethan whole. His misery made him oddly sympathetic even as he fought to destroy Ethan in the flooded reservoir.',
    },
    {
        id: 'rose_winters',
        name: 'Rosemary "Rose" Winters',
        image: '/images/characters/rose_winters.jpg',
        affiliation: 'U.S. Government',
        status: 'Alive',
        firstAppearance: 'Resident Evil Village (2021)',
        games: ['Resident Evil Village (2021)', 'Resident Evil Village: Shadows of Rose DLC (2022)'],
        bio: 'Rosemary Winters is the daughter of Ethan and Mia Winters — conceived while Ethan was unknowingly composed of Mold, making Rose unique in that she was born with Mold-based powers of her own. As an infant she was fragmented into four vessels by Mother Miranda in her attempt to use her as a medium for the resurrection of her deceased daughter Eva. After Ethan rescued and reassembled her, Rose was raised under the oversight of Chris Redfield\'s organization. As a teenager she became a government agent struggling to control her formidable powers, facing the lingering legacy of the Mold in the Shadows of Rose DLC.',
    },
    {
        id: 'duke',
        name: 'The Duke',
        image: '/images/characters/duke.jpg',
        affiliation: 'Unknown',
        status: 'Alive',
        firstAppearance: 'Resident Evil Village (2021)',
        games: ['Resident Evil Village (2021)'],
        bio: 'The Duke is the mysterious, enormously rotund merchant who appears throughout the village offering Ethan weapons, upgrades, and supplies — somehow moving between locations that should be impossible to traverse, existing just outside the normal rules of the world. He is aware of far more than he reveals about the village\'s history and the nature of what Ethan faces. His nature and origin are never explained — he may not be entirely human — and his final farewell to Ethan carries the weight of someone who understood the full truth about Ethan long before Ethan himself did. He is a loving homage to RE4\'s Merchant.',
    },
    {
        id: 'kevin_ryman',
        name: 'Kevin Ryman',
        image: '/images/characters/kevin_ryman.jpg',
        affiliation: 'Raccoon City Police Department',
        status: 'Unknown',
        firstAppearance: 'Resident Evil Outbreak (2003)',
        games: ['Resident Evil Outbreak (2003)', 'Resident Evil Outbreak: File #2 (2004)'],
        bio: 'Kevin Ryman is a Raccoon City police officer and one of eight survivors playable in the Outbreak series. Known as a quick-draw specialist with a brash, overconfident personality, Kevin failed his initial S.T.A.R.S. entrance exam — a fact that haunts him throughout the outbreak. He compensates with raw shooting skill and a fierce protectiveness toward his fellow survivors. Despite his bravado, Kevin is fundamentally a decent cop who does his best to get innocent civilians out of a city spiraling into catastrophe.',
    },
    {
        id: 'mark_wilkins',
        name: 'Mark Wilkins',
        image: '/images/characters/mark_wilkins.jpg',
        affiliation: 'Independent',
        status: 'Unknown',
        firstAppearance: 'Resident Evil Outbreak (2003)',
        games: ['Resident Evil Outbreak (2003)', 'Resident Evil Outbreak: File #2 (2004)'],
        bio: 'Mark Wilkins is a Vietnam War veteran working as a security guard at J\'s Bar when the Raccoon City outbreak hits. The oldest survivor of the Outbreak group, Mark\'s military experience gives him exceptional stamina and resistance to damage, and he wields heavy weapons with practiced efficiency. He projects calm authority in crisis situations, providing a stabilizing presence for the group. His backstory — carrying psychological scars from the Vietnam War — gives him a depth that sets him apart from the other survivors.',
    },
    {
        id: 'jim_chapman',
        name: 'Jim Chapman',
        image: '/images/characters/jim_chapman.jpg',
        affiliation: 'Raccoon City (subway worker)',
        status: 'Unknown',
        firstAppearance: 'Resident Evil Outbreak (2003)',
        games: ['Resident Evil Outbreak (2003)', 'Resident Evil Outbreak: File #2 (2004)'],
        bio: 'Jim Chapman is a Raccoon City subway maintenance worker who is, by his own admission, profoundly unsuited for any kind of combat or crisis. Easily frightened and openly cowardly, Jim has the unique ability to play dead convincingly — a skill that proves surprisingly valuable when surrounded by zombies. His knowledge of Raccoon City\'s underground infrastructure makes him a useful guide, and his relatable terror amid extraordinary circumstances makes him one of the more human characters in the Outbreak series.',
    },
    {
        id: 'george_hamilton',
        name: 'George Hamilton',
        image: '/images/characters/george_hamilton.jpg',
        affiliation: 'Raccoon City Hospital',
        status: 'Unknown',
        firstAppearance: 'Resident Evil Outbreak (2003)',
        games: ['Resident Evil Outbreak (2003)', 'Resident Evil Outbreak: File #2 (2004)'],
        bio: 'Dr. George Hamilton is a surgeon at Raccoon General Hospital whose vital medical knowledge makes him the primary healer of the Outbreak survivor group. Composed and analytical, George approaches even extreme situations with a clinician\'s detachment, focusing on keeping his fellow survivors alive through any means available. His ability to craft powerful medicines and antidotes from environmental components makes him indispensable in the field, and his proximity to the hospital\'s research gives him unique insight into the early stages of the viral outbreak.',
    },
    {
        id: 'alyssa_ashcroft',
        name: 'Alyssa Ashcroft',
        image: '/images/characters/alyssa_ashcroft.jpg',
        affiliation: 'Raccoon City Press',
        status: 'Unknown',
        firstAppearance: 'Resident Evil Outbreak (2003)',
        games: ['Resident Evil Outbreak (2003)', 'Resident Evil Outbreak: File #2 (2004)'],
        bio: 'Alyssa Ashcroft is an investigative journalist for the Raccoon Press who was already digging into Umbrella\'s suspicious activities before the outbreak began. Sharp, tenacious, and self-reliant, her journalistic instincts lead her to valuable files and documents hidden throughout Raccoon City that other survivors might overlook. Quick with a lockpick and relying on agility and adaptability rather than brute strength, Alyssa\'s professional cynicism serves her well in a situation where everyone has something to hide.',
    },
    {
        id: 'yoko_suzuki',
        name: 'Yoko Suzuki',
        image: '/images/characters/yoko_suzuki.jpg',
        affiliation: 'Umbrella Corporation (former)',
        status: 'Unknown',
        firstAppearance: 'Resident Evil Outbreak (2003)',
        games: ['Resident Evil Outbreak (2003)', 'Resident Evil Outbreak: File #2 (2004)'],
        bio: 'Yoko Suzuki is a university student with a mysterious past — she was formerly an Umbrella researcher whose memories were suppressed after she witnessed something she was not supposed to see. Her fractured memory is slowly reassembled through documents she encounters during the outbreak, painting a disturbing picture of what Umbrella did to ensure her silence. Timid and uncertain, Yoko compensates through her unique large backpack — giving her far greater item-carrying capacity than other survivors — and her gradual recovery of her own identity forms a quiet emotional backbone across the Outbreak titles.',
    },
    {
        id: 'david_king',
        name: 'David King',
        image: '/images/characters/david_king.jpg',
        affiliation: 'Independent (plumber)',
        status: 'Unknown',
        firstAppearance: 'Resident Evil Outbreak (2003)',
        games: ['Resident Evil Outbreak (2003)', 'Resident Evil Outbreak: File #2 (2004)'],
        bio: 'David King is a plumber who happens to be in J\'s Bar when the outbreak begins — a stoic and resourceful loner whose real past is deliberately vague, hinted to involve criminal or mercenary activity. Skilled with tools and knives, David can craft makeshift weapons from everyday materials and maintains absolute calm under fire. He speaks sparingly and trusts no one easily, preferring to observe before acting. His practical skills and self-sufficiency make him one of the most capable pure survivors in the Outbreak group.',
    },
    {
        id: 'cindy_lennox',
        name: 'Cindy Lennox',
        image: '/images/characters/cindy_lennox.jpg',
        affiliation: 'J\'s Bar',
        status: 'Unknown',
        firstAppearance: 'Resident Evil Outbreak (2003)',
        games: ['Resident Evil Outbreak (2003)', 'Resident Evil Outbreak: File #2 (2004)'],
        bio: 'Cindy Lennox is a cheerful and kind-hearted waitress at J\'s Bar who proves to be one of the most resilient survivors of the Raccoon City outbreak. Her naturally nurturing personality and medical background allow her to support her fellow survivors with healing items more effectively than anyone else. Despite having no combat training, Cindy\'s optimism and refusal to abandon people in need make her the emotional heart of the Outbreak survivor group. She maintains her warmth even as the world collapses around her.',
    },
];